### PR TITLE
Add solution for exercise 02

### PR DESCRIPTION
**Pull request by Avenev47**

### CODE REVIEW

**Comment by code-of-tack** [comment]
Looks good, but the number_of_vowels function should not print the sentence. Instead it should return the number of vowels because that's the main job of the function. Modularity would means that any program can call this function if it needs the number of vowels

**Comment by Avenev47** [comment]
Ok got it ! I am going to fix it  Sent from Mail for Windows From: TackSent: 27 June 2023 16:35To: code-of-tack/PE23JUN001Cc: Avenev47; AuthorSubject: Re: [code-of-tack/PE23JUN001] Add solution for exercise 02 (PR #3) Looks good, but the number_of_vowels function should not print the sentence. Instead it should return the number of vowels because that's the main job of the function. Modularity would means that any program can call this function if it needs the number of vowels—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Avenev47** [comment]
i have made the necessary changes

**Review by code-of-tack — APPROVED** [review]
Looks good, it'll approve it for now, next time onwards follow the pattern provided in the solutions. Every company will work with a consistency of the pattern of code in their repository and you'll have to adapt to it.

**Pull request merged**
